export interface Lesson {
  id: string;
  number: number;
  title: string;
  durationMinutes: number;
  summary: string;
  content: {
    overview: string;
    keyConcepts: string[];
    formulaOrFramework?: {
      title: string;
      formula: string;
      notes?: string;
    };
    detailedBreakdown: string[];
    interviewTip: string;
  };
  quiz: {
    question: string;
    options: string[];
    correctIndex: number;
    explanation: string;
  };
}

export interface CourseDetail {
  id: string;
  title: string;
  description: string;
  category: 'technical' | 'behavioral' | 'market';
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: number;
  lessonsCount: number;
  lessons: Lesson[];
}

export const courseCurriculumData: Record<string, CourseDetail> = {
  'dcf-fundamentals': {
    id: 'dcf-fundamentals',
    title: 'DCF Modeling Fundamentals',
    description: 'Learn to build comprehensive DCF models from scratch with real-world examples',
    category: 'technical',
    difficulty: 'Intermediate',
    duration: 120,
    lessonsCount: 8,
    lessons: [
      {
        id: 'dcf-1',
        number: 1,
        title: 'Introduction to DCF & Valuation Rationale',
        durationMinutes: 12,
        summary: 'Understand intrinsic value versus relative valuation, and when a DCF is best suited.',
        content: {
          overview: 'Discounted Cash Flow (DCF) valuation is based on the principle that the value of any business equals the present value of all its future cash flows, discounted at a rate reflecting the riskiness of those cash flows.',
          keyConcepts: [
            'Intrinsic valuation measures cash generation independent of current market multiples.',
            'DCF is ideal for cash-generative businesses with predictable projections.',
            'Two approaches: Unlevered (Free Cash Flow to Firm) and Levered (Free Cash Flow to Equity).'
          ],
          formulaOrFramework: {
            title: 'Fundamental DCF Concept',
            formula: 'Enterprise Value = ∑ [ UFCF_t / (1 + WACC)^t ] + Terminal Value / (1 + WACC)^n',
            notes: 'Discount period typically extends 5 to 10 years into the future.'
          },
          detailedBreakdown: [
            'Phase 1: Forecast discrete cash flows over 5–10 years using operating assumptions.',
            'Phase 2: Estimate terminal value to capture all cash flows beyond the projection horizon.',
            'Phase 3: Discount both discrete cash flows and terminal value using WACC to determine Enterprise Value.'
          ],
          interviewTip: 'When asked why DCF might NOT be suitable, mention early-stage pre-revenue startups or financial institutions (banks/insurance) where debt is part of operations.'
        },
        quiz: {
          question: 'Why is a DCF rarely used to value commercial banks?',
          options: [
            'Banks do not generate any operating profit',
            'Debt for banks is part of the operational inventory, making working capital and FCFF meaningless',
            'Bank cash flows cannot be discounted using interest rates',
            'Regulatory bodies forbid DCF analysis for financial entities'
          ],
          correctIndex: 1,
          explanation: 'For banks, interest expense is an operating expense and debt is raw material for lending, making traditional Free Cash Flow to Firm (FCFF) inapplicable. Dividend Discount Models (DDM) are used instead.'
        }
      },
      {
        id: 'dcf-2',
        number: 2,
        title: 'Unlevered Free Cash Flow (FCFF) Formula',
        durationMinutes: 15,
        summary: 'Step-by-step breakdown of calculating Unlevered Free Cash Flow from EBIT.',
        content: {
          overview: 'Unlevered Free Cash Flow (UFCF or FCFF) is the cash generated by core operations available to ALL capital providers (both debt and equity holders) without debt financing costs.',
          keyConcepts: [
            'Start with EBIT (Operating Income), NOT Net Income.',
            'Calculate NOPAT (Net Operating Profit After Tax) = EBIT × (1 - Tax Rate).',
            'Add back Non-Cash Expenses (Depreciation & Amortization, Stock-Based Comp).',
            'Subtract Capital Expenditures (CapEx) to maintain/grow the asset base.',
            'Subtract Net Increase in Working Capital (ΔNWC).'
          ],
          formulaOrFramework: {
            title: 'FCFF Standard Formula',
            formula: 'UFCF = EBIT × (1 - t) + D&A - CapEx - ΔNWC',
            notes: 'If working capital increases, it consumes cash (cash outflow). If it decreases, it releases cash.'
          },
          detailedBreakdown: [
            'Operating Assets & Liabilities: ΔNWC = (Current Assets - Cash) - (Current Liabilities - Debt).',
            'Non-operating income/expenses (gains on investments, FX gains) must be excluded.',
            'Maintenance vs Growth CapEx: In simple DCFs they are aggregated together.'
          ],
          interviewTip: 'Interviewers love to ask: "If CapEx increases by $10, how does UFCF change?" Since CapEx is not tax-deductible immediately (only depreciated later), UFCF drops dollar-for-dollar by $10.'
        },
        quiz: {
          question: 'If accounts receivable increases by $20M in a fiscal year, what is the effect on UFCF?',
          options: [
            'UFCF increases by $20M because revenue was recognized',
            'UFCF is unchanged because accounts receivable is on the balance sheet',
            'UFCF decreases by $20M because revenue was booked but cash was not collected',
            'UFCF decreases by $20M × (1 - Tax Rate)'
          ],
          correctIndex: 2,
          explanation: 'An increase in Accounts Receivable means revenue was recorded on the income statement without actual cash collection. Working Capital increases, representing a $20M cash drain.'
        }
      },
      {
        id: 'dcf-3',
        number: 3,
        title: 'Forecasting Operating Drivers',
        durationMinutes: 15,
        summary: 'Building revenue models, margin profiles, and working capital schedules.',
        content: {
          overview: 'A robust DCF relies on realistic financial statement modeling rather than arbitrary percentage growth guesses.',
          keyConcepts: [
            'Revenue builds: Price × Volume or Segment-level growth drivers.',
            'Operating Leverage: Fixed vs. Variable costs determine how margins expand with volume.',
            'Working capital days: Days Sales Outstanding (DSO), Days Inventory Outstanding (DIO), Days Payables Outstanding (DPO).'
          ],
          formulaOrFramework: {
            title: 'Cash Conversion Cycle (CCC)',
            formula: 'CCC = DSO + DIO - DPO',
            notes: 'Negative CCC means the business is funded by its suppliers (e.g. Amazon, Dell).'
          },
          detailedBreakdown: [
            'Forecast revenue by geography, unit volume, or cohort retention.',
            'Forecast COGS and SG&A as percentage of revenue or step-fixed costs.',
            'Tie D&A to a detailed PP&E roll-forward schedule.'
          ],
          interviewTip: 'Always check if projected margins exceed peer group averages. In pitch decks, aggressive margin expansion without justification is an immediate red flag.'
        },
        quiz: {
          question: 'What does a high Days Payables Outstanding (DPO) indicate for a company?',
          options: [
            'The company is unable to collect bills from its customers',
            'The company retains cash longer before paying suppliers, improving working capital',
            'The company has high inventory holding costs',
            'The company is insolvent'
          ],
          correctIndex: 1,
          explanation: 'DPO measures how long a company takes to pay its bills to suppliers. A higher DPO conserves cash in the short term, though excessively high DPO might damage supplier relationships.'
        }
      },
      {
        id: 'dcf-4',
        number: 4,
        title: 'Estimating WACC & Cost of Capital',
        durationMinutes: 18,
        summary: 'Deep dive into CAPM, Beta un-levering/re-levering, and capital structure weights.',
        content: {
          overview: 'The Weighted Average Cost of Capital (WACC) is the required return of the firm\'s capital providers, reflecting the blended risk of debt and equity.',
          keyConcepts: [
            'Cost of Equity (Re) via Capital Asset Pricing Model (CAPM): Rf + β × ERP.',
            'After-tax Cost of Debt: Rd × (1 - Tax Rate) due to interest tax shield.',
            'Market weights (not book values) of Debt and Equity must be used.'
          ],
          formulaOrFramework: {
            title: 'Hamada Beta Unlevering / Relevering',
            formula: 'β_Unlevered = β_Levered / [ 1 + (1 - t) × (Debt / Equity) ]',
            notes: 'Strip out debt risk to compare peer asset risk, then re-lever to target debt/equity ratio.'
          },
          detailedBreakdown: [
            'Risk-Free Rate (Rf): Typically 10-year US Treasury yield.',
            'Equity Risk Premium (ERP): Historical market return minus Rf (typically 5.0% - 6.5%).',
            'Size premium or country risk premium added when valuing smaller or emerging market companies.'
          ],
          interviewTip: 'Why is Cost of Equity higher than Cost of Debt? 1) Debt is senior in the capital structure / liquidation waterfall; 2) Debt interest is tax-deductible; 3) Equity holders demand a premium for residual risk.'
        },
        quiz: {
          question: 'Why do we unlever and relever Beta when calculating WACC?',
          options: [
            'To convert historical accounting beta into forward-looking stock beta',
            'To isolate pure business risk across peers by removing capital structure differences, then re-applying the target firm\'s debt level',
            'To reduce the tax burden of the target company',
            'To account for inflation and currency fluctuations'
          ],
          correctIndex: 1,
          explanation: 'Different peer companies have different debt loads. Unlevering removes the financial risk attributable to each company\'s debt, allowing you to find the median asset beta, and relevering applies the target company\'s financial structure.'
        }
      },
      {
        id: 'dcf-5',
        number: 5,
        title: 'Calculating Terminal Value',
        durationMinutes: 15,
        summary: 'Comparing Gordon Growth Model and Exit Multiple Method, plus sanity-checking implied multiples.',
        content: {
          overview: 'Terminal Value (TV) frequently accounts for 65% to 85% of total Enterprise Value in a DCF. Small changes in terminal assumptions produce dramatic valuation shifts.',
          keyConcepts: [
            'Perpetual Growth Method (Gordon Growth): Assumes steady state growth forever.',
            'Exit Multiple Method: Applies EV/EBITDA or EV/EBIT multiple in the final projection year.',
            'Long-term growth rate should NEVER exceed the long-term GDP growth rate of the economy (typically 2% - 3%).'
          ],
          formulaOrFramework: {
            title: 'Gordon Growth Terminal Value',
            formula: 'TV = [ UFCF_n × (1 + g) ] / (WACC - g)',
            notes: 'Where g is the perpetual growth rate and n is the final forecast year.'
          },
          detailedBreakdown: [
            'Always cross-check: calculate the implied exit multiple from the Gordon Growth output.',
            'If implied EV/EBITDA is 25x while peer trading comps are 12x, the growth rate is unrealistically high.',
            'Ensure the company has reached normalized steady-state reinvestment (CapEx ≈ D&A).'
          ],
          interviewTip: 'When asked which method is preferred by bankers: In M&A deals, Exit Multiple is most common because it grounds the valuation in prevailing market deals. In academic or fairness opinions, Gordon Growth is required for intrinsic defense.'
        },
        quiz: {
          question: 'What happens to Terminal Value if WACC decreases while the long-term growth rate (g) stays constant?',
          options: [
            'Terminal Value decreases',
            'Terminal Value increases because the denominator (WACC - g) shrinks',
            'Terminal Value is unaffected because cash flows do not change',
            'Terminal Value becomes negative'
          ],
          correctIndex: 1,
          explanation: 'In the formula TV = Cash Flow / (WACC - g), a lower WACC reduces the denominator, resulting in a substantially higher present value and terminal value.'
        }
      },
      {
        id: 'dcf-6',
        number: 6,
        title: 'Discounting & EV-to-Equity Value Bridge',
        durationMinutes: 15,
        summary: 'Mid-year convention, discounting discrete flows, and the enterprise to equity value bridge.',
        content: {
          overview: 'After discounting all cash flows to get Enterprise Value, you must bridge to Equity Value (and per-share price) by adjusting for net debt and claims.',
          keyConcepts: [
            'Mid-Year Convention: Cash flows arrive evenly throughout the year, so discount period uses 0.5, 1.5, 2.5 instead of 1, 2, 3.',
            'Enterprise Value measures core operating assets.',
            'Equity Value represents value attributable strictly to common equity holders.'
          ],
          formulaOrFramework: {
            title: 'EV to Equity Value Bridge',
            formula: 'Equity Value = Enterprise Value - Total Debt + Cash & Cash Equivalents - Non-Controlling Interests - Preferred Stock',
            notes: 'Or simply: Equity Value = Enterprise Value - Net Debt - Other Claims.'
          },
          detailedBreakdown: [
            'Add back non-operating assets: Excess cash, liquid marketable securities, equity method investments.',
            'Subtract debt-like items: Capital leases, unfunded pension obligations, restructuring liabilities.',
            'Divide Equity Value by fully diluted shares outstanding (using Treasury Stock Method for options/RSUs) to get Implied Share Price.'
          ],
          interviewTip: 'Why do we add cash to Enterprise Value to get Equity Value? Because cash is non-operating; Enterprise Value only valued the operating business, so cash must be returned to equity owners.'
        },
        quiz: {
          question: 'Which of the following is subtracted from Enterprise Value when bridging to Equity Value?',
          options: [
            'Cash and cash equivalents',
            'Long-term debt and capital leases',
            'Operating profit',
            'Accounts receivable'
          ],
          correctIndex: 1,
          explanation: 'Debt represents a senior financial claim on the business. Since Enterprise Value is the value to all capital providers, subtracting Debt gives the residual value remaining for equity holders.'
        }
      },
      {
        id: 'dcf-7',
        number: 7,
        title: 'Sensitivity Tables & Stress Testing',
        durationMinutes: 15,
        summary: 'Two-variable data tables in Excel and stress testing valuation ranges.',
        content: {
          overview: 'No single DCF output is presented as a point estimate. Bankers always present a valuation football field or 2D sensitivity matrix.',
          keyConcepts: [
            'Standard matrix 1: WACC (columns) vs. Terminal Growth Rate (rows).',
            'Standard matrix 2: WACC vs. Exit EBITDA Multiple.',
            'Identify valuation boundaries: Base, Bear, and Bull case scenarios.'
          ],
          formulaOrFramework: {
            title: 'Valuation Range Spread',
            formula: 'Football Field Chart = Min / 25th / Median / 75th / Max across DCF, Comps, and Precedents',
            notes: 'Typically shows DCF alongside Trading Comps, Precedent Transactions, and 52-week High/Low.'
          },
          detailedBreakdown: [
            'Step sizes: WACC increments of 0.50% (e.g. 8.0%, 8.5%, 9.0%, 9.5%, 10.0%).',
            'Growth rate increments of 0.25% (e.g. 2.0%, 2.25%, 2.5%, 2.75%, 3.0%).',
            'Color scales in Excel: Green for higher valuation, Red for lower valuation.'
          ],
          interviewTip: 'In interviews, emphasize that sensitivity analysis reveals which assumptions the investment thesis is most vulnerable to (e.g. pricing power vs cost of debt).'
        },
        quiz: {
          question: 'What is the primary purpose of a DCF Sensitivity Table?',
          options: [
            'To ensure the model complies with SEC accounting guidelines',
            'To eliminate all forecasting uncertainty',
            'To show how the implied share price reacts to variations in key inputs like WACC and terminal growth',
            'To calculate the exact historical tax liability'
          ],
          correctIndex: 2,
          explanation: 'A sensitivity table clearly demonstrates how sensitive valuation is to critical assumptions, showing the realistic range of outcomes for investment committees and clients.'
        }
      },
      {
        id: 'dcf-8',
        number: 8,
        title: 'Top DCF Interview Questions & Traps',
        durationMinutes: 15,
        summary: 'Mastering the most frequently asked technical interview questions and tricky nuances.',
        content: {
          overview: 'Investment banking interviewers test both your rote memory of formulas and your conceptual intuition of how corporate events flow through a DCF.',
          keyConcepts: [
            '"Walk me through a DCF" in 90 seconds or less.',
            'Working capital changes, tax rate changes, and interest rate spikes.',
            'Enterprise Value vs Equity Value consistency.'
          ],
          formulaOrFramework: {
            title: 'The Golden Consistency Rule',
            formula: 'UFCF ⇄ WACC ⇄ Enterprise Value  |  LFCF ⇄ Cost of Equity ⇄ Equity Value',
            notes: 'Never discount Unlevered FCF with Cost of Equity, or Levered FCF with WACC!'
          },
          detailedBreakdown: [
            'Question: "Can a DCF give a negative Enterprise Value?" Yes, if future cash flows are deeply negative and terminal value cannot offset them.',
            'Question: "What has a greater impact on DCF: a 1% change in revenue or 1% change in discount rate?" Usually discount rate, because it affects every single year and the entire terminal value compounded.',
            'Question: "How do you calculate fully diluted shares?" Common shares + in-the-money options/warrants net of buybacks via Treasury Stock Method.'
          ],
          interviewTip: 'Always speak with structured bullet points: "I would structure my response in three main phases: forecasting cash flows, discounting, and bridging to equity value."'
        },
        quiz: {
          question: 'If you discount Levered Free Cash Flow (LFCF) using WACC, what is the error?',
          options: [
            'There is no error; LFCF and UFCF both use WACC',
            'Double-counting the effect of debt, because interest is already subtracted in LFCF and debt cost is in WACC',
            'The valuation becomes infinite',
            'Net working capital is excluded'
          ],
          correctIndex: 1,
          explanation: 'Levered Free Cash Flow already accounts for debt service (interest and mandatory repayments). Discounting it by WACC (which includes the cost of debt) double-counts debt effects. LFCF must be discounted by Cost of Equity.'
        }
      }
    ]
  },
  'lbo-analysis': {
    id: 'lbo-analysis',
    title: 'LBO Analysis Deep Dive',
    description: 'Master leveraged buyout modeling and analysis techniques',
    category: 'technical',
    difficulty: 'Advanced',
    duration: 180,
    lessonsCount: 12,
    lessons: [
      {
        id: 'lbo-1',
        number: 1,
        title: 'LBO Fundamentals & Private Equity Mechanics',
        durationMinutes: 15,
        summary: 'Why private equity uses leverage to amplify equity returns.',
        content: {
          overview: 'A Leveraged Buyout (LBO) is the acquisition of a target company using a substantial amount of borrowed money (debt) to fund the purchase price, with the target\'s cash flows used to service and pay down debt over time.',
          keyConcepts: [
            'Debt acts as financial leverage: smaller initial equity check yields higher returns on exit.',
            'Target profile: High recurring cash flows, low CapEx, defensive market position, strong asset base.',
            'Holding period is typically 3 to 7 years.'
          ],
          formulaOrFramework: {
            title: 'Core Returns Metrics',
            formula: 'MoIC = Total Equity Distributed / Initial Equity Invested  |  IRR = (MoIC)^(1/t) - 1',
            notes: 'A 2.0x MoIC in 3 years = ~26% IRR. A 2.0x MoIC in 5 years = ~15% IRR.'
          },
          detailedBreakdown: [
            'Sponsor contributes 30%-50% equity; remaining 50%-70% funded by senior and subordinated debt.',
            'Cash generation during ownership is swept to amortize debt.',
            'Upon sale/exit, debt is paid off, leaving all residual equity for the sponsor.'
          ],
          interviewTip: 'Compare buying a house with a mortgage to buying a company in an LBO. Down payment = Sponsor Equity; Mortgage = Bank Debt; Selling the home after 5 years = PE Exit.'
        },
        quiz: {
          question: 'What is the primary financial reason private equity firms use high debt levels in an LBO?',
          options: [
            'To avoid paying any capital gains tax upon exit',
            'To reduce the equity investment required, thereby maximizing Internal Rate of Return (IRR)',
            'To eliminate all operational risks of the business',
            'Because debt never has to be paid back'
          ],
          correctIndex: 1,
          explanation: 'Using debt minimizes the initial equity check. If the company performs well and pays down debt, the equity value expands significantly, driving up IRR and multiple on invested capital.'
        }
      },
      {
        id: 'lbo-2',
        number: 2,
        title: 'Sources & Uses of Funds Table',
        durationMinutes: 15,
        summary: 'Building the foundational Sources & Uses schedule for an LBO.',
        content: {
          overview: 'The Sources & Uses table dictates where the deal financing comes from and exactly where every dollar is spent at closing. Total Sources MUST equal Total Uses.',
          keyConcepts: [
            'Uses: Purchase Equity Value, Refinance existing target debt, Advisory and financing fees, Minimum cash on balance sheet.',
            'Sources: Revolver, Term Loan A & B, Senior Notes, Mezzanine / Subordinated Debt, Sponsor Equity.',
            'Sponsor equity is the "plug" that balances the equation.'
          ],
          formulaOrFramework: {
            title: 'Sources & Uses Balance',
            formula: 'Total Sources = Total Uses  |  Sponsor Equity = Total Uses - Total Debt Raised',
            notes: 'Financing fees are capitalized and amortized; advisory fees are expensed at closing.'
          },
          detailedBreakdown: [
            'Calculate Purchase Price based on offer per share or headline Enterprise Value multiple.',
            'Account for existing debt: If old debt is refinanced, it enters Uses; if rolled over, it enters both Sources and Uses.',
            'Management Rollover: Existing management rolls their equity into the new entity.'
          ],
          interviewTip: 'When asked how transaction fees are treated: financing fees (debt issuance) are deducted from the debt balance on the balance sheet and amortized; advisory/legal fees are subtracted directly from cash/retained earnings.'
        },
        quiz: {
          question: 'If Total Uses in an LBO equals $1,000M and debt financing provides $650M, what is the Sponsor Equity check?',
          options: [
            '$650M',
            '$1,000M',
            '$350M',
            '$1,650M'
          ],
          correctIndex: 2,
          explanation: 'Sponsor Equity is the balancing figure: Total Uses ($1,000M) minus Total Debt Sources ($650M) = $350M equity required.'
        }
      },
      {
        id: 'lbo-3',
        number: 3,
        title: 'Debt Tranches & Financing Structure',
        durationMinutes: 15,
        summary: 'Senior secured bank debt, Term Loans, High Yield bonds, and Unitranche loans.',
        content: {
          overview: 'Different debt tranches carry distinct interest rates, covenants, tenors, and seniority in liquidation.',
          keyConcepts: [
            'Revolving Credit Facility: Short-term liquidity line, floating rate (SOFR + spread).',
            'Term Loan A (Amortizing) & Term Loan B (Institutional): 1% annual amortization, 6-7 year tenor.',
            'Senior Notes / High Yield: Fixed coupon, bullet repayment at maturity, incurrence covenants.'
          ],
          formulaOrFramework: {
            title: 'Leverage Multiple Limits',
            formula: 'Total Leverage = Total Debt / LTM EBITDA  (typically 4.0x - 6.5x)',
            notes: 'Senior Secured Leverage is typically capped at 3.0x - 4.0x EBITDA.'
          },
          detailedBreakdown: [
            'Maintenance covenants: Borrower must maintain specific leverage and interest coverage metrics quarterly.',
            'Incurrence covenants: Borrower is restricted from taking specific actions (like taking on more debt or paying dividends) unless tests are met.',
            'Private credit funds increasingly provide single unitranche facilities up to 6.0x leverage.'
          ],
          interviewTip: 'Why would a PE sponsor prefer High Yield over Bank Debt even with higher interest? High Yield bonds have no mandatory annual principal amortization and looser incurrence covenants, leaving more free cash flow for growth.'
        },
        quiz: {
          question: 'What is the main difference between maintenance covenants and incurrence covenants?',
          options: [
            'Maintenance covenants are only used for government bonds',
            'Maintenance covenants require periodic compliance checks (e.g. leverage < 4.0x quarterly), while incurrence covenants only trigger when a company undertakes a specific event (e.g. issuing debt)',
            'Incurrence covenants apply only to equity holders',
            'Maintenance covenants have no legal enforceability'
          ],
          correctIndex: 1,
          explanation: 'Bank debt typically features maintenance covenants that test financial ratios every quarter. High yield bonds have incurrence covenants that only restrict specific actions (like taking on more debt or issuing a dividend).'
        }
      },
      {
        id: 'lbo-4',
        number: 4,
        title: 'Three-Statement Projection & Debt Waterfall',
        durationMinutes: 18,
        summary: 'Modeling the cash sweep, debt paydown hierarchy, and circular interest formulas.',
        content: {
          overview: 'The debt schedule dictates the priority order of cash allocation: operating expenses → mandatory debt service → discretionary debt prepayment (cash sweep).',
          keyConcepts: [
            'Cash Available for Debt Service (CADS) = Cash from Operations - Maintenance CapEx - Minimum Cash Balance.',
            'Mandatory Amortization: Term Loan A (5-10%/yr), Term Loan B (1%/yr).',
            '100% Excess Cash Sweep: Remaining cash pays down prepayable debt (Revolver, then Term Loans).'
          ],
          formulaOrFramework: {
            title: 'Debt Paydown Waterfall Order',
            formula: '1. Pay Revolver balance  →  2. Mandatory Term Loan payments  →  3. Voluntary prepayment via Excess Cash Sweep',
            notes: 'High yield bonds typically have prepayment penalties (call premiums) and are not swept.'
          },
          detailedBreakdown: [
            'Track opening balance, interest accrued, mandatory repayment, voluntary prepayment, and closing balance for each tranche.',
            'Calculate interest expense based on Average Balance: (Opening + Closing) / 2 to avoid distortion.',
            'Circular reference resolution: Use Excel iteration toggle or opening balance interest approximation.'
          ],
          interviewTip: 'If asked: "What happens if Free Cash Flow is negative in year 2?" The company draws on its Revolving Credit Facility to cover cash shortfalls; if the Revolver maxes out, it faces a liquidity crisis or default.'
        },
        quiz: {
          question: 'In a standard debt schedule, which debt tranche is paid down first during an excess cash sweep?',
          options: [
            'Subordinated Mezzanine Notes',
            'Revolving Credit Facility and Senior Term Loans (prepayable without penalty)',
            'Senior Unsecured Notes with 10-year maturity',
            'Preferred Equity'
          ],
          correctIndex: 1,
          explanation: 'Revolvers and Term Loans are senior bank facilities that permit prepayment without costly call protection penalties, making them the first priority for cash sweeps.'
        }
      },
      {
        id: 'lbo-5',
        number: 5,
        title: 'Exit Scenarios & Returns Attribution',
        durationMinutes: 15,
        summary: 'Calculating exit Enterprise Value, resolving debt obligations, and unpacking the 3 value creation drivers.',
        content: {
          overview: 'At exit (year 3, 5, or 7), the private equity sponsor sells the company to a strategic buyer, another sponsor (secondary buyout), or goes public via IPO.',
          keyConcepts: [
            'Exit Enterprise Value = Exit EBITDA × Exit Multiple.',
            'Exit Equity Value = Exit Enterprise Value - Ending Debt + Ending Cash.',
            'Returns breakdown: 1) EBITDA Growth, 2) Multiple Expansion/Contraction, 3) Deleveraging (Debt Paydown).'
          ],
          formulaOrFramework: {
            title: 'Value Creation Triad',
            formula: 'Δ Equity Value = (Δ EBITDA × Exit Multiple) + (EBITDA_entry × Δ Multiple) + Total Debt Paid Down',
            notes: 'Conservative PE underwriting assumes multiple contraction (Exit multiple < Entry multiple).'
          },
          detailedBreakdown: [
            'Multiple contraction risk: If entry was 12x, underwriting often models an exit at 10x or 11x.',
            'EBITDA growth driver: Organic revenue growth + margin expansion initiatives.',
            'Deleveraging: Target debt paid down from free cash generation increases equity portion.'
          ],
          interviewTip: 'When asked what makes a good LBO candidate in interviews, mention: "Stable recurring cash flows, pricing power, low ongoing CapEx requirements, clear cost reduction levers, and multiple exit avenues."'
        },
        quiz: {
          question: 'If a sponsor buys a company at 10x EBITDA and exits at 10x EBITDA with zero EBITDA growth, how does it generate an investment return?',
          options: [
            'It cannot make any return without EBITDA growth or multiple expansion',
            'By using operating cash flow to pay down debt, converting debt into equity value (deleveraging)',
            'By collecting dividends funded by secondary loans only',
            'Through currency appreciation'
          ],
          correctIndex: 1,
          explanation: 'Even with zero growth and zero multiple expansion, paying off debt with the company\'s operational cash flow reduces net debt. Since Equity Value = Enterprise Value - Net Debt, paying down debt directly transfers enterprise value to the equity holder.'
        }
      },
      {
        id: 'lbo-6',
        number: 6,
        title: 'Paper LBO in 5 Minutes (Mental Math)',
        durationMinutes: 15,
        summary: 'Fast mental math techniques for private equity interview tests without a computer.',
        content: {
          overview: 'The "Paper LBO" is the benchmark private equity modeling interview test. You are given 5 minutes and a blank piece of paper to compute IRR and MoIC.',
          keyConcepts: [
            'Round numbers aggressively and master key MoIC-to-IRR benchmarks.',
            'Calculate cumulative FCF over 5 years and subtract from initial debt.',
            'Compute Exit Equity and divide by Entry Sponsor Equity.'
          ],
          formulaOrFramework: {
            title: 'Key 5-Year IRR Benchmarks to Memorize',
            formula: '2.0x in 5 yrs ≈ 15% IRR  |  2.5x in 5 yrs ≈ 20% IRR  |  3.0x in 5 yrs ≈ 25% IRR',
            notes: '3-year rules: 2.0x in 3 yrs ≈ 26% IRR  |  3.0x in 3 yrs ≈ 44% IRR.'
          },
          detailedBreakdown: [
            'Step 1: Calculate Purchase Price = Entry Multiple × Entry EBITDA.',
            'Step 2: Determine Debt vs Equity (e.g. 60% Debt, 40% Sponsor Equity).',
            'Step 3: Forecast Year 5 EBITDA (using given growth rate).',
            'Step 4: Estimate cumulative cash generated available for debt paydown.',
            'Step 5: Calculate Exit EV = Year 5 EBITDA × Exit Multiple; Exit Equity = Exit EV - Remaining Debt.',
            'Step 6: MoIC = Exit Equity / Entry Equity. Convert to IRR.'
          ],
          interviewTip: 'Write out your steps cleanly with labels. Interviewers care more about your structured thinking and sanity checking than carrying exact decimals.'
        },
        quiz: {
          question: 'In a 5-year investment, doubling your money (2.0x MoIC) corresponds approximately to what IRR?',
          options: [
            '10% IRR',
            '15% IRR',
            '25% IRR',
            '35% IRR'
          ],
          correctIndex: 1,
          explanation: '2.0^(1/5) - 1 = 14.87%, which rounds to ~15% IRR. This is a fundamental private equity interview benchmark.'
        }
      }
    ]
  },
  'behavioral-mastery': {
    id: 'behavioral-mastery',
    title: 'Behavioral Interview Mastery',
    description: 'STAR method and banking-specific behavioral questions',
    category: 'behavioral',
    difficulty: 'Beginner',
    duration: 90,
    lessonsCount: 6,
    lessons: [
      {
        id: 'beh-1',
        number: 1,
        title: 'The Banking Behavioral Framework & STAR Method',
        durationMinutes: 12,
        summary: 'How bankers evaluate fit, stamina, attention to detail, and poise.',
        content: {
          overview: 'Behavioral and fit questions determine whether junior bankers would want to spend 80+ hours a week working beside you in the bullpen under tight deadlines.',
          keyConcepts: [
            'S - Situation: Set the scene in 15-20 seconds (company, role, challenge).',
            'T - Task: Specify the exact responsibility you held.',
            'A - Action: Spend 60% of your time here on what YOU specifically did.',
            'R - Result: Quantifiable outcome, business impact, and key learning.'
          ],
          formulaOrFramework: {
            title: 'The 2-Minute Rule',
            formula: 'Target answer length: 90 to 120 seconds. Anything over 2.5 minutes loses the interviewer\'s attention.',
            notes: 'Structure answers with signposting: "First, I audited the model; second, I stress-tested assumptions..."'
          },
          detailedBreakdown: [
            'Keep 5-6 versatile stories prepared that can flex across leadership, conflict, failure, and analytical problem-solving.',
            'Always frame teamwork constructively; avoid assigning blame to colleagues.',
            'Quantify outcomes whenever possible (saved $X, improved turnaround time by Y%, delivered on a 48-hour deadline).'
          ],
          interviewTip: 'End every STAR story with a reflective takeaway: "That experience taught me the importance of proactive communication when managing competing deadlines."'
        },
        quiz: {
          question: 'What percentage of a STAR method answer should focus on the "Action" component?',
          options: [
            '10%',
            '25%',
            '60%',
            '95%'
          ],
          correctIndex: 2,
          explanation: 'The Action section shows your individual decision-making, analytical rigor, and work ethic. Spending ~60% of your answer on Action ensures the interviewer understands your direct contributions.'
        }
      },
      {
        id: 'beh-2',
        number: 2,
        title: 'Crafting "Walk Me Through Your Resume"',
        durationMinutes: 15,
        summary: 'Your 90-second personal narrative that sets the tone for the entire interview.',
        content: {
          overview: 'This is the opening question in 95% of banking interviews. A great answer is not a chronological recitation of bullets, but a cohesive story with momentum.',
          keyConcepts: [
            'Four acts: 1) University/Origins & initial passion for finance, 2) Key milestones & analytical progression, 3) Real-world deal or project catalyst, 4) Why you are here today.',
            'Every career transition must feel logical and intentional.',
            'Show humility paired with high hunger and intellectual curiosity.'
          ],
          formulaOrFramework: {
            title: 'Resume Pitch Formula',
            formula: 'Origins/Spark  →  Analytical Progression  →  Defining Project/Experience  →  Why This Firm Today',
            notes: 'Time benchmark: 90 seconds to max 2 minutes.'
          },
          detailedBreakdown: [
            'Do NOT read your resume line by line.',
            'Emphasize the catalyst that pushed you toward M&A / Investment Banking.',
            'Tailor the final sentence directly to the bank you are interviewing with.'
          ],
          interviewTip: 'Practice timing yourself with a stopwatch. The most common mistake is rambling for 4-5 minutes on college clubs before even reaching relevant internships.'
        },
        quiz: {
          question: 'What is the primary objective of "Walk me through your resume" in a banking interview?',
          options: [
            'To recite every bullet point and GPA score from your resume',
            'To deliver a concise, logical narrative explaining why every step has prepared you to excel as an investment banking analyst at this firm',
            'To explain your personal hobbies and childhood memories',
            'To test your knowledge of macroeconomics'
          ],
          correctIndex: 1,
          explanation: 'The interviewers already read your resume. They want to see if you can synthesize your journey into a compelling, logical narrative demonstrating clear motivation and fit for their platform.'
        }
      },
      {
        id: 'beh-3',
        number: 3,
        title: '"Why Investment Banking?" & "Why This Bank?"',
        durationMinutes: 15,
        summary: 'Avoiding generic clichés and proving authentic motivation.',
        content: {
          overview: 'Junior banking involves intense hours and high-stress environments. Bankers want proof that you understand the day-to-day realities and will not quit after three months.',
          keyConcepts: [
            'Avoid generic answers: "I love fast-paced environments" or "I want to work with smart people."',
            'Three-pillar structure: 1) Steepest learning curve in corporate finance, 2) Tangible transaction advisory at the board level, 3) Proven interest through past experience.',
            'Why This Bank: Cite specific recent deals, banker conversations, and platform culture.'
          ],
          formulaOrFramework: {
            title: 'Why This Bank Trifecta',
            formula: 'Specific Deal Announced + Banker Interaction / Culture + Platform Strategic Moat',
            notes: 'Example: "I followed your lead advisory on Deal X, and after speaking with Analyst Y, the lean team culture stood out."'
          },
          detailedBreakdown: [
            'Mention bankers you networked with by name (with their permission).',
            'Highlight deal specialization: "Your Healthcare M&A team advised on the $4B cross-border acquisition of..."',
            'Show that you understand the analyst role: building pitch books, financial modeling, management presentations, and data room management.'
          ],
          interviewTip: 'Never mention compensation, prestige, or exit opportunities into private equity as reasons why you want to do investment banking.'
        },
        quiz: {
          question: 'Which of the following is the STRONGEST response to "Why our bank?"',
          options: [
            '"Your bank pays top of the Street compensation and has great exit opportunities"',
            '"I really liked the coffee in your lobby and your website looks modern"',
            '"In speaking with Associate Sarah Chen on your Industrials team, I learned about the lean deal team dynamic, and I closely followed your lead advisory on the $3.2B acquisition of XYZ Corp"',
            '"I applied to all bulge bracket banks and want whoever offers me a job first"'
          ],
          correctIndex: 2,
          explanation: 'A strong answer demonstrates genuine homework: referencing specific professionals you spoke with, knowledge of specific deals the group advised on, and understanding the group culture.'
        }
      }
    ]
  },
  'ma-transactions': {
    id: 'ma-transactions',
    title: 'M&A Transaction Analysis',
    description: 'Understand M&A processes, valuation, and deal structures',
    category: 'technical',
    difficulty: 'Intermediate',
    duration: 150,
    lessonsCount: 10,
    lessons: [
      {
        id: 'ma-1',
        number: 1,
        title: 'M&A Strategic Rationale & Deal Dynamics',
        durationMinutes: 15,
        summary: 'Buy-side vs. sell-side M&A advisory and strategic vs. financial acquirers.',
        content: {
          overview: 'Mergers and acquisitions (M&A) are corporate transactions where companies combine or acquire one another to accelerate growth, consolidate market share, or capture operational synergies.',
          keyConcepts: [
            'Strategic Acquirers (Corporates): Seek synergies, market expansion, IP, or talent. Can pay higher multiples.',
            'Financial Acquirers (Private Equity): Seek cash generation, operational improvements, and multiple expansion with target hurdle IRRs.',
            'Horizontal M&A (competitor consolidation) vs. Vertical M&A (supply chain integration).'
          ],
          formulaOrFramework: {
            title: 'Synergy Valuation Rule',
            formula: 'Value of Synergies = PV(Annual Synergies - Integration Costs) / WACC',
            notes: 'Cost synergies are given higher valuation credit than revenue synergies by equity research analysts.'
          },
          detailedBreakdown: [
            'Cost Synergies: Eliminating redundant corporate headquarters, IT consolidation, joint purchasing power.',
            'Revenue Synergies: Cross-selling products to target\'s distribution network, entering new geographies.',
            'Acquirer willingness to pay: Maximum Offer Price = Target Standalone Value + Net Present Value of Synergies.'
          ],
          interviewTip: 'When asked why most M&A deals fail to create shareholder value: cite cultural clash, overestimating revenue synergies, and integration execution failure.'
        },
        quiz: {
          question: 'Why can a strategic acquirer typically pay a higher purchase price than a financial sponsor (PE firm)?',
          options: [
            'Strategic acquirers do not have to follow antitrust regulations',
            'Strategic acquirers can realize operational and cost synergies that reduce effective purchase price, whereas financial sponsors typically cannot',
            'Strategic acquirers have lower accounting standards',
            'Financial sponsors are not permitted to use debt'
          ],
          correctIndex: 1,
          explanation: 'Strategic buyers can eliminate overlapping departments, combine purchasing power, and cross-sell products, creating real dollar synergies that justify paying a control premium.'
        }
      }
    ]
  },
  'accretion-dilution': {
    id: 'accretion-dilution',
    title: 'Accretion/Dilution Analysis',
    description: 'Master EPS accretion and dilution calculations in M&A scenarios',
    category: 'technical',
    difficulty: 'Advanced',
    duration: 90,
    lessonsCount: 7,
    lessons: [
      {
        id: 'ad-1',
        number: 1,
        title: 'Accretion/Dilution Fundamentals & Core Definition',
        durationMinutes: 12,
        summary: 'Understanding Pro Forma EPS and Wall Street\'s obsession with earnings accretion.',
        content: {
          overview: 'Accretion/Dilution analysis determines whether a proposed M&A transaction will increase (accretive) or decrease (dilutive) the acquirer\'s pro forma Earnings Per Share (EPS).',
          keyConcepts: [
            'Accretive: Pro Forma EPS > Acquirer Standalone EPS.',
            'Dilutive: Pro Forma EPS < Acquirer Standalone EPS.',
            'Dilution does not automatically mean a deal is bad long-term, but it often triggers near-term stock sell-offs.'
          ],
          formulaOrFramework: {
            title: 'Pro Forma EPS Formula',
            formula: 'Pro Forma EPS = Combined Net Income / Combined Diluted Shares Outstanding',
            notes: 'Combined Net Income = Acquirer Net Income + Target Net Income + After-tax Synergies - After-tax Transaction Costs - New Interest Expense + Foregone Interest on Cash.'
          },
          detailedBreakdown: [
            'Step 1: Calculate standalone net income for Acquirer and Target.',
            'Step 2: Add after-tax operational synergies and subtract deal financing costs.',
            'Step 3: Calculate new shares issued if stock was used in purchase consideration.',
            'Step 4: Compare Pro Forma EPS to Acquirer standalone EPS.'
          ],
          interviewTip: 'Master the 100% Stock Rule: In a 100% stock-for-stock deal with no synergies, the deal is accretive if the Acquirer P/E multiple is HIGHER than the Target P/E multiple!'
        },
        quiz: {
          question: 'In an all-stock acquisition with zero synergies, if Company A (P/E of 20x) acquires Company B (P/E of 12x), is the deal accretive or dilutive?',
          options: [
            'Dilutive, because Company B is smaller',
            'Accretive, because the acquirer has a higher P/E multiple than the target',
            'Neutral (neither accretive nor dilutive)',
            'Impossible to tell without knowing share counts'
          ],
          correctIndex: 1,
          explanation: 'In an all-stock deal with no synergies, if Acquirer P/E > Target P/E, the deal is always ACCRETIVE. The acquirer pays less per dollar of target earnings than its own shares are valued at.'
        }
      }
    ]
  },
  'market-knowledge': {
    id: 'market-knowledge',
    title: 'Investment Banking Market Knowledge',
    description: 'Current market trends, league tables, and industry insights',
    category: 'market',
    difficulty: 'Intermediate',
    duration: 110,
    lessonsCount: 9,
    lessons: [
      {
        id: 'mk-1',
        number: 1,
        title: 'Macro Environment & Interest Rate Cycles',
        durationMinutes: 15,
        summary: 'How central bank monetary policy, yield curves, and inflation shape M&A and capital markets.',
        content: {
          overview: 'Investment bankers must constantly monitor macro conditions because interest rates directly dictate debt financing availability, leveraged buyout math, and corporate M&A appetite.',
          keyConcepts: [
            'Fed Funds Rate & SOFR: Cost of corporate borrowing.',
            'Inverted Yield Curve: Historically a leading indicator of economic slowdown.',
            'Cost of Capital Impact: Higher rates increase WACC, lowering DCF valuation multiples.'
          ],
          formulaOrFramework: {
            title: 'Rate Impact on Dealmaking',
            formula: 'Higher Rates  →  Cost of Debt ↑  →  LBO Leverage Capacity ↓  →  Valuation Multiples Compress',
            notes: 'In high-rate regimes, all-equity or stock-for-stock deals and earnouts proliferate.'
          },
          detailedBreakdown: [
            'IPO Windows: Volatility index (VIX) > 25 typically shuts the public IPO window.',
            'Private Credit: Direct lenders stepped in when syndicated loan markets retrenched.',
            'Cross-border FX volatility affects multinational deal certainty and hedging costs.'
          ],
          interviewTip: 'When asked "Where is the 10-Year Treasury yield today?", know the approximate current number (~4.0%-4.5%) and explain how it affects discount rates and risk premiums.'
        },
        quiz: {
          question: 'When the Federal Reserve increases interest rates, what is the typical direct effect on LBO valuations?',
          options: [
            'LBO valuations expand because sponsors have more cash',
            'LBO valuations compress because borrowing costs rise, reducing the amount of debt sponsors can support',
            'Interest rates have no impact on leveraged buyouts',
            'High yield bonds automatically convert into equity'
          ],
          correctIndex: 1,
          explanation: 'Higher interest rates increase interest expense on Term Loans and Notes, decreasing the maximum debt multiple a target company can safely service and forcing sponsors to lower acquisition multiples.'
        }
      }
    ]
  }
};
